version: '2'
services:
    web:
      container_name: python
      build: ./app  
      ports:
        - "5000:5000"
      depends_on:
          - redis
    redis:
        image: redis
        container_name: redis