apiVersion: batch/v1
kind: CronJob
metadata:
  name: datacenter
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-datacenter
            image: httpd:latest
            imagePullPolicy: IfNotPresent
            command:
            - echo Welcome to xfusioncorp!
          restartPolicy: OnFailure