apiVersion: v1
kind: Secret
metadata:
  name: ecommerce
type: Opaque
stringData:
  license-number: 5ecur3

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
spec:
  containers:
    - name: secret-container-devops
      image: ubuntu:latest
      command: ["/bin/bash", "-c","sleep 10000"]
      volumeMounts:
        - name: secret-mount
          mountPath: /opt/games
          readOnly: true
  volumes:
    - name: secret-mount
      secret:
        secretName: ecommerce