apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd-app
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      resources:
        requests:
          memory: "15Mi"
          cpu: "100m"
        limits:
          memory: "20Mi"
          cpu: "100m"
