apiVersion: v1
kind: Namespace
metadata:
  name: devops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  labels:
    app: httpd-deploy
  namespace: devops
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: httpd-deploy
  template:
    metadata:
      labels:
        app: httpd-deploy
    spec:
      containers:
        - name: httpd
          image: httpd:2.4.25
          ports:
            - containerPort: 80
              name: http-web-svc


---

apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: httpd-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-web-svc
      nodePort: 30008

# Perform rolling update
# k set image deployments/httpd-deploy httpd=httpd:2.4.43 -n devops
# Perform the rollback
# k rollout undo deployment/httpd-deploy -n devops