apiVersion: v1
kind: Namespace
metadata:
  name: devops

# Blue Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: httpd
  namespace: devops
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: httpd
      env: blue
  template:
    metadata:
      labels:
        app: httpd
        env: blue
    spec:
      containers:
        - name: httpd-container
          image: httpd:2.4
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: devops
spec:
  type: NodePort
  selector:
    app: httpd
    env: blue
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
