apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: custom-provisioner
spec:
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["t3a.small"]