apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: custom-provisioner
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3a.small", t2.small]
    #- key: karpenter.k8s.aws/instance-size
    #  operator: In
    #  values: ["nano", "micro", "small"]        
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]